apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenie-mvp-backend-dev
  namespace: backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
        - name: greenie-backend
          image: ghcr.io/greenie-one/backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 900
