name: Update types

on:
  [push]
  # branches:
  #   - 'dev'
  #   - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          repository: greenie-one/global-dtos
          path: global-dtos
          # ref: ${{ steps.extract_branch.outputs.branch }}
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Copy files and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Greenie"

          sh $GITHUB_WORKSPACE/backend/scripts/copy_dto.sh

          cd $GITHUB_WORKSPACE/global-dtos
          git checkout -B ${GITHUB_REF##*/}

          git add -A
          git diff-index --quiet HEAD -- || git commit -m "Types sync"
          git push --set-upstream origin ${GITHUB_REF##*/}

